namespace ParkingProject
{
    partial class CustomerRegisterForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CustomerRegisterForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Content = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.phonenumberTextBox7 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.codemelliTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lastNameTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.FirstNameTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuButton7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CarinformationTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Content.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // Content
            // 
            this.Content.Controls.Add(this.bunifuButton1);
            this.Content.Controls.Add(this.bunifuButton4);
            this.Content.Controls.Add(this.bunifuPanel1);
            this.Content.Controls.Add(this.lastNameTextBox5);
            this.Content.Controls.Add(this.FirstNameTextBox4);
            this.Content.Controls.Add(this.bunifuGroupBox1);
            this.Content.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Content.Location = new System.Drawing.Point(0, 0);
            this.Content.Name = "Content";
            this.Content.Size = new System.Drawing.Size(806, 511);
            this.Content.TabIndex = 10;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Exit";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(421, 434);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 20;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 20;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 20;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 20;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 21;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Save";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges2;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeft = null;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRight = null;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton4.IdleBorderRadius = 0;
            this.bunifuButton4.IdleBorderThickness = 0;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(222, 434);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.OnDisabledState.BorderRadius = 20;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.BorderRadius = 20;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.BorderRadius = 20;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = null;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.BorderRadius = 20;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton4.TabIndex = 21;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            this.bunifuButton4.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(806, 43);
            this.bunifuPanel1.TabIndex = 19;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(89, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(120, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Customer and Car";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // phonenumberTextBox7
            // 
            this.phonenumberTextBox7.AcceptsReturn = false;
            this.phonenumberTextBox7.AcceptsTab = false;
            this.phonenumberTextBox7.AnimationSpeed = 200;
            this.phonenumberTextBox7.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonenumberTextBox7.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonenumberTextBox7.AutoSizeHeight = true;
            this.phonenumberTextBox7.BackColor = System.Drawing.Color.Transparent;
            this.phonenumberTextBox7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonenumberTextBox7.BackgroundImage")));
            this.phonenumberTextBox7.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phonenumberTextBox7.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonenumberTextBox7.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phonenumberTextBox7.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonenumberTextBox7.BorderRadius = 1;
            this.phonenumberTextBox7.BorderThickness = 1;
            this.phonenumberTextBox7.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonenumberTextBox7.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberTextBox7.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phonenumberTextBox7.DefaultText = "";
            this.phonenumberTextBox7.FillColor = System.Drawing.Color.White;
            this.phonenumberTextBox7.HideSelection = true;
            this.phonenumberTextBox7.IconLeft = null;
            this.phonenumberTextBox7.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberTextBox7.IconPadding = 10;
            this.phonenumberTextBox7.IconRight = null;
            this.phonenumberTextBox7.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonenumberTextBox7.Lines = new string[0];
            this.phonenumberTextBox7.Location = new System.Drawing.Point(442, 145);
            this.phonenumberTextBox7.MaxLength = 32767;
            this.phonenumberTextBox7.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonenumberTextBox7.Modified = false;
            this.phonenumberTextBox7.Multiline = false;
            this.phonenumberTextBox7.Name = "phonenumberTextBox7";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberTextBox7.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonenumberTextBox7.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberTextBox7.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonenumberTextBox7.OnIdleState = stateProperties16;
            this.phonenumberTextBox7.Padding = new System.Windows.Forms.Padding(3);
            this.phonenumberTextBox7.PasswordChar = '\0';
            this.phonenumberTextBox7.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phonenumberTextBox7.PlaceholderText = "Phone Number";
            this.phonenumberTextBox7.ReadOnly = false;
            this.phonenumberTextBox7.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonenumberTextBox7.SelectedText = "";
            this.phonenumberTextBox7.SelectionLength = 0;
            this.phonenumberTextBox7.SelectionStart = 0;
            this.phonenumberTextBox7.ShortcutsEnabled = true;
            this.phonenumberTextBox7.Size = new System.Drawing.Size(260, 39);
            this.phonenumberTextBox7.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonenumberTextBox7.TabIndex = 8;
            this.phonenumberTextBox7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonenumberTextBox7.TextMarginBottom = 0;
            this.phonenumberTextBox7.TextMarginLeft = 3;
            this.phonenumberTextBox7.TextMarginTop = 1;
            this.phonenumberTextBox7.TextPlaceholder = "Phone Number";
            this.phonenumberTextBox7.UseSystemPasswordChar = false;
            this.phonenumberTextBox7.WordWrap = true;
            // 
            // codemelliTextBox6
            // 
            this.codemelliTextBox6.AcceptsReturn = false;
            this.codemelliTextBox6.AcceptsTab = false;
            this.codemelliTextBox6.AnimationSpeed = 200;
            this.codemelliTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.codemelliTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.codemelliTextBox6.AutoSizeHeight = true;
            this.codemelliTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.codemelliTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("codemelliTextBox6.BackgroundImage")));
            this.codemelliTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.codemelliTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.codemelliTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.codemelliTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
            this.codemelliTextBox6.BorderRadius = 1;
            this.codemelliTextBox6.BorderThickness = 1;
            this.codemelliTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.codemelliTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.codemelliTextBox6.DefaultText = "";
            this.codemelliTextBox6.FillColor = System.Drawing.Color.White;
            this.codemelliTextBox6.HideSelection = true;
            this.codemelliTextBox6.IconLeft = null;
            this.codemelliTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox6.IconPadding = 10;
            this.codemelliTextBox6.IconRight = null;
            this.codemelliTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox6.Lines = new string[0];
            this.codemelliTextBox6.Location = new System.Drawing.Point(442, 53);
            this.codemelliTextBox6.MaxLength = 32767;
            this.codemelliTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
            this.codemelliTextBox6.Modified = false;
            this.codemelliTextBox6.Multiline = false;
            this.codemelliTextBox6.Name = "codemelliTextBox6";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox6.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.codemelliTextBox6.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox6.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox6.OnIdleState = stateProperties20;
            this.codemelliTextBox6.Padding = new System.Windows.Forms.Padding(3);
            this.codemelliTextBox6.PasswordChar = '\0';
            this.codemelliTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.codemelliTextBox6.PlaceholderText = "Code Melli";
            this.codemelliTextBox6.ReadOnly = false;
            this.codemelliTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.codemelliTextBox6.SelectedText = "";
            this.codemelliTextBox6.SelectionLength = 0;
            this.codemelliTextBox6.SelectionStart = 0;
            this.codemelliTextBox6.ShortcutsEnabled = true;
            this.codemelliTextBox6.Size = new System.Drawing.Size(260, 39);
            this.codemelliTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.codemelliTextBox6.TabIndex = 9;
            this.codemelliTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.codemelliTextBox6.TextMarginBottom = 0;
            this.codemelliTextBox6.TextMarginLeft = 3;
            this.codemelliTextBox6.TextMarginTop = 1;
            this.codemelliTextBox6.TextPlaceholder = "Code Melli";
            this.codemelliTextBox6.UseSystemPasswordChar = false;
            this.codemelliTextBox6.WordWrap = true;
            // 
            // lastNameTextBox5
            // 
            this.lastNameTextBox5.AcceptsReturn = false;
            this.lastNameTextBox5.AcceptsTab = false;
            this.lastNameTextBox5.AnimationSpeed = 200;
            this.lastNameTextBox5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameTextBox5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameTextBox5.AutoSizeHeight = true;
            this.lastNameTextBox5.BackColor = System.Drawing.Color.Transparent;
            this.lastNameTextBox5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameTextBox5.BackgroundImage")));
            this.lastNameTextBox5.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lastNameTextBox5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastNameTextBox5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lastNameTextBox5.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastNameTextBox5.BorderRadius = 1;
            this.lastNameTextBox5.BorderThickness = 1;
            this.lastNameTextBox5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastNameTextBox5.DefaultText = "";
            this.lastNameTextBox5.FillColor = System.Drawing.Color.White;
            this.lastNameTextBox5.HideSelection = true;
            this.lastNameTextBox5.IconLeft = null;
            this.lastNameTextBox5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.IconPadding = 10;
            this.lastNameTextBox5.IconRight = null;
            this.lastNameTextBox5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.Lines = new string[0];
            this.lastNameTextBox5.Location = new System.Drawing.Point(74, 216);
            this.lastNameTextBox5.MaxLength = 32767;
            this.lastNameTextBox5.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastNameTextBox5.Modified = false;
            this.lastNameTextBox5.Multiline = false;
            this.lastNameTextBox5.Name = "lastNameTextBox5";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastNameTextBox5.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnIdleState = stateProperties4;
            this.lastNameTextBox5.Padding = new System.Windows.Forms.Padding(3);
            this.lastNameTextBox5.PasswordChar = '\0';
            this.lastNameTextBox5.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameTextBox5.PlaceholderText = "Last Name";
            this.lastNameTextBox5.ReadOnly = false;
            this.lastNameTextBox5.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameTextBox5.SelectedText = "";
            this.lastNameTextBox5.SelectionLength = 0;
            this.lastNameTextBox5.SelectionStart = 0;
            this.lastNameTextBox5.ShortcutsEnabled = true;
            this.lastNameTextBox5.Size = new System.Drawing.Size(260, 39);
            this.lastNameTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastNameTextBox5.TabIndex = 11;
            this.lastNameTextBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameTextBox5.TextMarginBottom = 0;
            this.lastNameTextBox5.TextMarginLeft = 3;
            this.lastNameTextBox5.TextMarginTop = 1;
            this.lastNameTextBox5.TextPlaceholder = "Last Name";
            this.lastNameTextBox5.UseSystemPasswordChar = false;
            this.lastNameTextBox5.WordWrap = true;
            // 
            // FirstNameTextBox4
            // 
            this.FirstNameTextBox4.AcceptsReturn = false;
            this.FirstNameTextBox4.AcceptsTab = false;
            this.FirstNameTextBox4.AnimationSpeed = 200;
            this.FirstNameTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.FirstNameTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.FirstNameTextBox4.AutoSizeHeight = true;
            this.FirstNameTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.FirstNameTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("FirstNameTextBox4.BackgroundImage")));
            this.FirstNameTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.FirstNameTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.FirstNameTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.FirstNameTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.FirstNameTextBox4.BorderRadius = 1;
            this.FirstNameTextBox4.BorderThickness = 1;
            this.FirstNameTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.FirstNameTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.FirstNameTextBox4.DefaultText = "";
            this.FirstNameTextBox4.FillColor = System.Drawing.Color.White;
            this.FirstNameTextBox4.HideSelection = true;
            this.FirstNameTextBox4.IconLeft = null;
            this.FirstNameTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.IconPadding = 10;
            this.FirstNameTextBox4.IconRight = null;
            this.FirstNameTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.Lines = new string[0];
            this.FirstNameTextBox4.Location = new System.Drawing.Point(74, 124);
            this.FirstNameTextBox4.MaxLength = 32767;
            this.FirstNameTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
            this.FirstNameTextBox4.Modified = false;
            this.FirstNameTextBox4.Multiline = false;
            this.FirstNameTextBox4.Name = "FirstNameTextBox4";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.FirstNameTextBox4.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnIdleState = stateProperties8;
            this.FirstNameTextBox4.Padding = new System.Windows.Forms.Padding(3);
            this.FirstNameTextBox4.PasswordChar = '\0';
            this.FirstNameTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.FirstNameTextBox4.PlaceholderText = "First Name";
            this.FirstNameTextBox4.ReadOnly = false;
            this.FirstNameTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.FirstNameTextBox4.SelectedText = "";
            this.FirstNameTextBox4.SelectionLength = 0;
            this.FirstNameTextBox4.SelectionStart = 0;
            this.FirstNameTextBox4.ShortcutsEnabled = true;
            this.FirstNameTextBox4.Size = new System.Drawing.Size(260, 39);
            this.FirstNameTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.FirstNameTextBox4.TabIndex = 13;
            this.FirstNameTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.FirstNameTextBox4.TextMarginBottom = 0;
            this.FirstNameTextBox4.TextMarginLeft = 3;
            this.FirstNameTextBox4.TextMarginTop = 1;
            this.FirstNameTextBox4.TextPlaceholder = "First Name";
            this.FirstNameTextBox4.UseSystemPasswordChar = false;
            this.FirstNameTextBox4.WordWrap = true;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuButton7);
            this.bunifuGroupBox1.Controls.Add(this.CarinformationTextBox1);
            this.bunifuGroupBox1.Controls.Add(this.phonenumberTextBox7);
            this.bunifuGroupBox1.Controls.Add(this.codemelliTextBox6);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(33, 71);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(740, 337);
            this.bunifuGroupBox1.TabIndex = 20;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Enter Customer Information";
            // 
            // bunifuButton7
            // 
            this.bunifuButton7.AllowAnimations = true;
            this.bunifuButton7.AllowMouseEffects = true;
            this.bunifuButton7.AllowToggling = false;
            this.bunifuButton7.AnimationSpeed = 200;
            this.bunifuButton7.AutoGenerateColors = false;
            this.bunifuButton7.AutoRoundBorders = false;
            this.bunifuButton7.AutoSizeLeftIcon = true;
            this.bunifuButton7.AutoSizeRightIcon = true;
            this.bunifuButton7.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton7.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.BackgroundImage")));
            this.bunifuButton7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.ButtonText = "";
            this.bunifuButton7.ButtonTextMarginLeft = 0;
            this.bunifuButton7.ColorContrastOnClick = 45;
            this.bunifuButton7.ColorContrastOnHover = 45;
            this.bunifuButton7.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton7.CustomizableEdges = borderEdges3;
            this.bunifuButton7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton7.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton7.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton7.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton7.ForeColor = System.Drawing.Color.White;
            this.bunifuButton7.IconLeft = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.IconLeft")));
            this.bunifuButton7.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton7.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton7.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton7.IconMarginLeft = 11;
            this.bunifuButton7.IconPadding = 10;
            this.bunifuButton7.IconRight = null;
            this.bunifuButton7.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton7.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton7.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton7.IconSize = 25;
            this.bunifuButton7.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton7.IdleBorderRadius = 0;
            this.bunifuButton7.IdleBorderThickness = 0;
            this.bunifuButton7.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton7.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.IdleIconLeftImage")));
            this.bunifuButton7.IdleIconRightImage = null;
            this.bunifuButton7.IndicateFocus = false;
            this.bunifuButton7.Location = new System.Drawing.Point(532, 240);
            this.bunifuButton7.Name = "bunifuButton7";
            this.bunifuButton7.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton7.OnDisabledState.BorderRadius = 1;
            this.bunifuButton7.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnDisabledState.BorderThickness = 1;
            this.bunifuButton7.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton7.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton7.OnDisabledState.IconLeftImage = null;
            this.bunifuButton7.OnDisabledState.IconRightImage = null;
            this.bunifuButton7.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton7.onHoverState.BorderRadius = 1;
            this.bunifuButton7.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.onHoverState.BorderThickness = 1;
            this.bunifuButton7.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton7.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton7.onHoverState.IconLeftImage = null;
            this.bunifuButton7.onHoverState.IconRightImage = null;
            this.bunifuButton7.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(222)))), ((int)(((byte)(252)))));
            this.bunifuButton7.OnIdleState.BorderRadius = 1;
            this.bunifuButton7.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnIdleState.BorderThickness = 1;
            this.bunifuButton7.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(222)))), ((int)(((byte)(252)))));
            this.bunifuButton7.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton7.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.OnIdleState.IconLeftImage")));
            this.bunifuButton7.OnIdleState.IconRightImage = null;
            this.bunifuButton7.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton7.OnPressedState.BorderRadius = 1;
            this.bunifuButton7.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton7.OnPressedState.BorderThickness = 1;
            this.bunifuButton7.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton7.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton7.OnPressedState.IconLeftImage = null;
            this.bunifuButton7.OnPressedState.IconRightImage = null;
            this.bunifuButton7.Size = new System.Drawing.Size(45, 39);
            this.bunifuButton7.TabIndex = 10;
            this.bunifuButton7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton7.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton7.TextMarginLeft = 0;
            this.bunifuButton7.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton7.UseDefaultRadiusAndThickness = true;
            this.bunifuButton7.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // CarinformationTextBox1
            // 
            this.CarinformationTextBox1.AcceptsReturn = false;
            this.CarinformationTextBox1.AcceptsTab = false;
            this.CarinformationTextBox1.AnimationSpeed = 200;
            this.CarinformationTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CarinformationTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CarinformationTextBox1.AutoSizeHeight = true;
            this.CarinformationTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.CarinformationTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CarinformationTextBox1.BackgroundImage")));
            this.CarinformationTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CarinformationTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CarinformationTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CarinformationTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.CarinformationTextBox1.BorderRadius = 1;
            this.CarinformationTextBox1.BorderThickness = 1;
            this.CarinformationTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CarinformationTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CarinformationTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.CarinformationTextBox1.DefaultText = "";
            this.CarinformationTextBox1.FillColor = System.Drawing.Color.White;
            this.CarinformationTextBox1.HideSelection = true;
            this.CarinformationTextBox1.IconLeft = null;
            this.CarinformationTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CarinformationTextBox1.IconPadding = 10;
            this.CarinformationTextBox1.IconRight = null;
            this.CarinformationTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CarinformationTextBox1.Lines = new string[0];
            this.CarinformationTextBox1.Location = new System.Drawing.Point(41, 240);
            this.CarinformationTextBox1.MaxLength = 32767;
            this.CarinformationTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.CarinformationTextBox1.Modified = false;
            this.CarinformationTextBox1.Multiline = false;
            this.CarinformationTextBox1.Name = "CarinformationTextBox1";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CarinformationTextBox1.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CarinformationTextBox1.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CarinformationTextBox1.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CarinformationTextBox1.OnIdleState = stateProperties12;
            this.CarinformationTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.CarinformationTextBox1.PasswordChar = '\0';
            this.CarinformationTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CarinformationTextBox1.PlaceholderText = "Car Information";
            this.CarinformationTextBox1.ReadOnly = false;
            this.CarinformationTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CarinformationTextBox1.SelectedText = "";
            this.CarinformationTextBox1.SelectionLength = 0;
            this.CarinformationTextBox1.SelectionStart = 0;
            this.CarinformationTextBox1.ShortcutsEnabled = true;
            this.CarinformationTextBox1.Size = new System.Drawing.Size(472, 39);
            this.CarinformationTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CarinformationTextBox1.TabIndex = 14;
            this.CarinformationTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CarinformationTextBox1.TextMarginBottom = 0;
            this.CarinformationTextBox1.TextMarginLeft = 3;
            this.CarinformationTextBox1.TextMarginTop = 1;
            this.CarinformationTextBox1.TextPlaceholder = "Car Information";
            this.CarinformationTextBox1.UseSystemPasswordChar = false;
            this.CarinformationTextBox1.WordWrap = true;
            // 
            // CustomerRegisterForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(806, 511);
            this.Controls.Add(this.Content);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "CustomerRegisterForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "CustomerRegisterForm";
            this.Activated += new System.EventHandler(this.CustomerRegisterForm_Activated);
            this.Content.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel Content;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton7;
        public Bunifu.UI.WinForms.BunifuTextBox CarinformationTextBox1;
        public Bunifu.UI.WinForms.BunifuTextBox phonenumberTextBox7;
        public Bunifu.UI.WinForms.BunifuTextBox codemelliTextBox6;
        public Bunifu.UI.WinForms.BunifuTextBox lastNameTextBox5;
        public Bunifu.UI.WinForms.BunifuTextBox FirstNameTextBox4;
    }
}