namespace ParkingProject
{
    partial class Employeeusercontrol
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Employeeusercontrol));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Content = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.employeetypeDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.salaryTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.codemelliTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ageTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.employeeidTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lastNameTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.FirstNameTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Content.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Content
            // 
            this.Content.Controls.Add(this.lastNameTextBox5);
            this.Content.Controls.Add(this.FirstNameTextBox4);
            this.Content.Controls.Add(this.bunifuPanel1);
            this.Content.Controls.Add(this.bunifuButton1);
            this.Content.Controls.Add(this.bunifuButton3);
            this.Content.Controls.Add(this.employeetypeDropdown1);
            this.Content.Controls.Add(this.salaryTextBox4);
            this.Content.Controls.Add(this.codemelliTextBox3);
            this.Content.Controls.Add(this.ageTextBox2);
            this.Content.Controls.Add(this.employeeidTextBox1);
            this.Content.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Content.Location = new System.Drawing.Point(0, 0);
            this.Content.Name = "Content";
            this.Content.Size = new System.Drawing.Size(1175, 642);
            this.Content.TabIndex = 0;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Back";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges3;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(639, 532);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 3;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Save";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges4;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeft = null;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRight = null;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleBorderRadius = 0;
            this.bunifuButton3.IdleBorderThickness = 0;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(412, 532);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton3.TabIndex = 3;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // employeetypeDropdown1
            // 
            this.employeetypeDropdown1.BackColor = System.Drawing.Color.Transparent;
            this.employeetypeDropdown1.BackgroundColor = System.Drawing.Color.White;
            this.employeetypeDropdown1.BorderColor = System.Drawing.Color.Silver;
            this.employeetypeDropdown1.BorderRadius = 1;
            this.employeetypeDropdown1.Color = System.Drawing.Color.Silver;
            this.employeetypeDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.employeetypeDropdown1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.employeetypeDropdown1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeetypeDropdown1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.employeetypeDropdown1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.employeetypeDropdown1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.employeetypeDropdown1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.employeetypeDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.employeetypeDropdown1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.employeetypeDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.employeetypeDropdown1.FillDropDown = true;
            this.employeetypeDropdown1.FillIndicator = false;
            this.employeetypeDropdown1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.employeetypeDropdown1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.employeetypeDropdown1.ForeColor = System.Drawing.Color.Black;
            this.employeetypeDropdown1.FormattingEnabled = true;
            this.employeetypeDropdown1.Icon = null;
            this.employeetypeDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.employeetypeDropdown1.IndicatorColor = System.Drawing.Color.DarkGray;
            this.employeetypeDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.employeetypeDropdown1.IndicatorThickness = 2;
            this.employeetypeDropdown1.IsDropdownOpened = false;
            this.employeetypeDropdown1.ItemBackColor = System.Drawing.Color.White;
            this.employeetypeDropdown1.ItemBorderColor = System.Drawing.Color.White;
            this.employeetypeDropdown1.ItemForeColor = System.Drawing.Color.Black;
            this.employeetypeDropdown1.ItemHeight = 26;
            this.employeetypeDropdown1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.employeetypeDropdown1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.employeetypeDropdown1.Items.AddRange(new object[] {
            "Regular",
            "Manager",
            "Owner"});
            this.employeetypeDropdown1.ItemTopMargin = 3;
            this.employeetypeDropdown1.Location = new System.Drawing.Point(476, 364);
            this.employeetypeDropdown1.Name = "employeetypeDropdown1";
            this.employeetypeDropdown1.Size = new System.Drawing.Size(260, 32);
            this.employeetypeDropdown1.TabIndex = 1;
            this.employeetypeDropdown1.Text = "Employee type";
            this.employeetypeDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.employeetypeDropdown1.TextLeftMargin = 5;
            // 
            // salaryTextBox4
            // 
            this.salaryTextBox4.AcceptsReturn = false;
            this.salaryTextBox4.AcceptsTab = false;
            this.salaryTextBox4.AnimationSpeed = 200;
            this.salaryTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.salaryTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.salaryTextBox4.AutoSizeHeight = true;
            this.salaryTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.salaryTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("salaryTextBox4.BackgroundImage")));
            this.salaryTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.salaryTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.salaryTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.salaryTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.salaryTextBox4.BorderRadius = 1;
            this.salaryTextBox4.BorderThickness = 1;
            this.salaryTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.salaryTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.salaryTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.salaryTextBox4.DefaultText = "";
            this.salaryTextBox4.FillColor = System.Drawing.Color.White;
            this.salaryTextBox4.HideSelection = true;
            this.salaryTextBox4.IconLeft = null;
            this.salaryTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.salaryTextBox4.IconPadding = 10;
            this.salaryTextBox4.IconRight = null;
            this.salaryTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.salaryTextBox4.Lines = new string[0];
            this.salaryTextBox4.Location = new System.Drawing.Point(800, 253);
            this.salaryTextBox4.MaxLength = 32767;
            this.salaryTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
            this.salaryTextBox4.Modified = false;
            this.salaryTextBox4.Multiline = false;
            this.salaryTextBox4.Name = "salaryTextBox4";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salaryTextBox4.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.salaryTextBox4.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salaryTextBox4.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salaryTextBox4.OnIdleState = stateProperties36;
            this.salaryTextBox4.Padding = new System.Windows.Forms.Padding(3);
            this.salaryTextBox4.PasswordChar = '\0';
            this.salaryTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.salaryTextBox4.PlaceholderText = "Salary";
            this.salaryTextBox4.ReadOnly = false;
            this.salaryTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.salaryTextBox4.SelectedText = "";
            this.salaryTextBox4.SelectionLength = 0;
            this.salaryTextBox4.SelectionStart = 0;
            this.salaryTextBox4.ShortcutsEnabled = true;
            this.salaryTextBox4.Size = new System.Drawing.Size(260, 39);
            this.salaryTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.salaryTextBox4.TabIndex = 0;
            this.salaryTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.salaryTextBox4.TextMarginBottom = 0;
            this.salaryTextBox4.TextMarginLeft = 3;
            this.salaryTextBox4.TextMarginTop = 1;
            this.salaryTextBox4.TextPlaceholder = "Salary";
            this.salaryTextBox4.UseSystemPasswordChar = false;
            this.salaryTextBox4.WordWrap = true;
            // 
            // codemelliTextBox3
            // 
            this.codemelliTextBox3.AcceptsReturn = false;
            this.codemelliTextBox3.AcceptsTab = false;
            this.codemelliTextBox3.AnimationSpeed = 200;
            this.codemelliTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.codemelliTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.codemelliTextBox3.AutoSizeHeight = true;
            this.codemelliTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.codemelliTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("codemelliTextBox3.BackgroundImage")));
            this.codemelliTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.codemelliTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.codemelliTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.codemelliTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.codemelliTextBox3.BorderRadius = 1;
            this.codemelliTextBox3.BorderThickness = 1;
            this.codemelliTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.codemelliTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.codemelliTextBox3.DefaultText = "";
            this.codemelliTextBox3.FillColor = System.Drawing.Color.White;
            this.codemelliTextBox3.HideSelection = true;
            this.codemelliTextBox3.IconLeft = null;
            this.codemelliTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox3.IconPadding = 10;
            this.codemelliTextBox3.IconRight = null;
            this.codemelliTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.codemelliTextBox3.Lines = new string[0];
            this.codemelliTextBox3.Location = new System.Drawing.Point(476, 253);
            this.codemelliTextBox3.MaxLength = 32767;
            this.codemelliTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.codemelliTextBox3.Modified = false;
            this.codemelliTextBox3.Multiline = false;
            this.codemelliTextBox3.Name = "codemelliTextBox3";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox3.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.codemelliTextBox3.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox3.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codemelliTextBox3.OnIdleState = stateProperties40;
            this.codemelliTextBox3.Padding = new System.Windows.Forms.Padding(3);
            this.codemelliTextBox3.PasswordChar = '\0';
            this.codemelliTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.codemelliTextBox3.PlaceholderText = "Code melli";
            this.codemelliTextBox3.ReadOnly = false;
            this.codemelliTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.codemelliTextBox3.SelectedText = "";
            this.codemelliTextBox3.SelectionLength = 0;
            this.codemelliTextBox3.SelectionStart = 0;
            this.codemelliTextBox3.ShortcutsEnabled = true;
            this.codemelliTextBox3.Size = new System.Drawing.Size(260, 39);
            this.codemelliTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.codemelliTextBox3.TabIndex = 0;
            this.codemelliTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.codemelliTextBox3.TextMarginBottom = 0;
            this.codemelliTextBox3.TextMarginLeft = 3;
            this.codemelliTextBox3.TextMarginTop = 1;
            this.codemelliTextBox3.TextPlaceholder = "Code melli";
            this.codemelliTextBox3.UseSystemPasswordChar = false;
            this.codemelliTextBox3.WordWrap = true;
            // 
            // ageTextBox2
            // 
            this.ageTextBox2.AcceptsReturn = false;
            this.ageTextBox2.AcceptsTab = false;
            this.ageTextBox2.AnimationSpeed = 200;
            this.ageTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ageTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ageTextBox2.AutoSizeHeight = true;
            this.ageTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.ageTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ageTextBox2.BackgroundImage")));
            this.ageTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ageTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ageTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ageTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.ageTextBox2.BorderRadius = 1;
            this.ageTextBox2.BorderThickness = 1;
            this.ageTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ageTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ageTextBox2.DefaultText = "";
            this.ageTextBox2.FillColor = System.Drawing.Color.White;
            this.ageTextBox2.HideSelection = true;
            this.ageTextBox2.IconLeft = null;
            this.ageTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTextBox2.IconPadding = 10;
            this.ageTextBox2.IconRight = null;
            this.ageTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTextBox2.Lines = new string[0];
            this.ageTextBox2.Location = new System.Drawing.Point(800, 137);
            this.ageTextBox2.MaxLength = 32767;
            this.ageTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.ageTextBox2.Modified = false;
            this.ageTextBox2.Multiline = false;
            this.ageTextBox2.Name = "ageTextBox2";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTextBox2.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ageTextBox2.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTextBox2.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTextBox2.OnIdleState = stateProperties44;
            this.ageTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.ageTextBox2.PasswordChar = '\0';
            this.ageTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ageTextBox2.PlaceholderText = "Age";
            this.ageTextBox2.ReadOnly = false;
            this.ageTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ageTextBox2.SelectedText = "";
            this.ageTextBox2.SelectionLength = 0;
            this.ageTextBox2.SelectionStart = 0;
            this.ageTextBox2.ShortcutsEnabled = true;
            this.ageTextBox2.Size = new System.Drawing.Size(260, 39);
            this.ageTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ageTextBox2.TabIndex = 0;
            this.ageTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ageTextBox2.TextMarginBottom = 0;
            this.ageTextBox2.TextMarginLeft = 3;
            this.ageTextBox2.TextMarginTop = 1;
            this.ageTextBox2.TextPlaceholder = "Age";
            this.ageTextBox2.UseSystemPasswordChar = false;
            this.ageTextBox2.WordWrap = true;
            // 
            // employeeidTextBox1
            // 
            this.employeeidTextBox1.AcceptsReturn = false;
            this.employeeidTextBox1.AcceptsTab = false;
            this.employeeidTextBox1.AnimationSpeed = 200;
            this.employeeidTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.employeeidTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.employeeidTextBox1.AutoSizeHeight = true;
            this.employeeidTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.employeeidTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("employeeidTextBox1.BackgroundImage")));
            this.employeeidTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.employeeidTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeeidTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.employeeidTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.employeeidTextBox1.BorderRadius = 1;
            this.employeeidTextBox1.BorderThickness = 1;
            this.employeeidTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.employeeidTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeidTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.employeeidTextBox1.DefaultText = "";
            this.employeeidTextBox1.FillColor = System.Drawing.Color.White;
            this.employeeidTextBox1.HideSelection = true;
            this.employeeidTextBox1.IconLeft = null;
            this.employeeidTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeidTextBox1.IconPadding = 10;
            this.employeeidTextBox1.IconRight = null;
            this.employeeidTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeidTextBox1.Lines = new string[0];
            this.employeeidTextBox1.Location = new System.Drawing.Point(476, 137);
            this.employeeidTextBox1.MaxLength = 32767;
            this.employeeidTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.employeeidTextBox1.Modified = false;
            this.employeeidTextBox1.Multiline = false;
            this.employeeidTextBox1.Name = "employeeidTextBox1";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeidTextBox1.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.employeeidTextBox1.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeidTextBox1.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeidTextBox1.OnIdleState = stateProperties48;
            this.employeeidTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.employeeidTextBox1.PasswordChar = '\0';
            this.employeeidTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.employeeidTextBox1.PlaceholderText = "Employee_id";
            this.employeeidTextBox1.ReadOnly = false;
            this.employeeidTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.employeeidTextBox1.SelectedText = "";
            this.employeeidTextBox1.SelectionLength = 0;
            this.employeeidTextBox1.SelectionStart = 0;
            this.employeeidTextBox1.ShortcutsEnabled = true;
            this.employeeidTextBox1.Size = new System.Drawing.Size(260, 39);
            this.employeeidTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.employeeidTextBox1.TabIndex = 0;
            this.employeeidTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.employeeidTextBox1.TextMarginBottom = 0;
            this.employeeidTextBox1.TextMarginLeft = 3;
            this.employeeidTextBox1.TextMarginTop = 1;
            this.employeeidTextBox1.TextPlaceholder = "Employee_id";
            this.employeeidTextBox1.UseSystemPasswordChar = false;
            this.employeeidTextBox1.WordWrap = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1175, 43);
            this.bunifuPanel1.TabIndex = 20;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(89, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(159, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Employee Registeration";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lastNameTextBox5
            // 
            this.lastNameTextBox5.AcceptsReturn = false;
            this.lastNameTextBox5.AcceptsTab = false;
            this.lastNameTextBox5.AnimationSpeed = 200;
            this.lastNameTextBox5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameTextBox5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameTextBox5.AutoSizeHeight = true;
            this.lastNameTextBox5.BackColor = System.Drawing.Color.Transparent;
            this.lastNameTextBox5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameTextBox5.BackgroundImage")));
            this.lastNameTextBox5.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lastNameTextBox5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastNameTextBox5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lastNameTextBox5.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastNameTextBox5.BorderRadius = 1;
            this.lastNameTextBox5.BorderThickness = 1;
            this.lastNameTextBox5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastNameTextBox5.DefaultText = "";
            this.lastNameTextBox5.FillColor = System.Drawing.Color.White;
            this.lastNameTextBox5.HideSelection = true;
            this.lastNameTextBox5.IconLeft = null;
            this.lastNameTextBox5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.IconPadding = 10;
            this.lastNameTextBox5.IconRight = null;
            this.lastNameTextBox5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTextBox5.Lines = new string[0];
            this.lastNameTextBox5.Location = new System.Drawing.Point(133, 253);
            this.lastNameTextBox5.MaxLength = 32767;
            this.lastNameTextBox5.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastNameTextBox5.Modified = false;
            this.lastNameTextBox5.Multiline = false;
            this.lastNameTextBox5.Name = "lastNameTextBox5";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastNameTextBox5.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTextBox5.OnIdleState = stateProperties28;
            this.lastNameTextBox5.Padding = new System.Windows.Forms.Padding(3);
            this.lastNameTextBox5.PasswordChar = '\0';
            this.lastNameTextBox5.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameTextBox5.PlaceholderText = "Last Name";
            this.lastNameTextBox5.ReadOnly = false;
            this.lastNameTextBox5.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameTextBox5.SelectedText = "";
            this.lastNameTextBox5.SelectionLength = 0;
            this.lastNameTextBox5.SelectionStart = 0;
            this.lastNameTextBox5.ShortcutsEnabled = true;
            this.lastNameTextBox5.Size = new System.Drawing.Size(260, 39);
            this.lastNameTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastNameTextBox5.TabIndex = 21;
            this.lastNameTextBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameTextBox5.TextMarginBottom = 0;
            this.lastNameTextBox5.TextMarginLeft = 3;
            this.lastNameTextBox5.TextMarginTop = 1;
            this.lastNameTextBox5.TextPlaceholder = "Last Name";
            this.lastNameTextBox5.UseSystemPasswordChar = false;
            this.lastNameTextBox5.WordWrap = true;
            // 
            // FirstNameTextBox4
            // 
            this.FirstNameTextBox4.AcceptsReturn = false;
            this.FirstNameTextBox4.AcceptsTab = false;
            this.FirstNameTextBox4.AnimationSpeed = 200;
            this.FirstNameTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.FirstNameTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.FirstNameTextBox4.AutoSizeHeight = true;
            this.FirstNameTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.FirstNameTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("FirstNameTextBox4.BackgroundImage")));
            this.FirstNameTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.FirstNameTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.FirstNameTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.FirstNameTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.FirstNameTextBox4.BorderRadius = 1;
            this.FirstNameTextBox4.BorderThickness = 1;
            this.FirstNameTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.FirstNameTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.FirstNameTextBox4.DefaultText = "";
            this.FirstNameTextBox4.FillColor = System.Drawing.Color.White;
            this.FirstNameTextBox4.HideSelection = true;
            this.FirstNameTextBox4.IconLeft = null;
            this.FirstNameTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.IconPadding = 10;
            this.FirstNameTextBox4.IconRight = null;
            this.FirstNameTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.FirstNameTextBox4.Lines = new string[0];
            this.FirstNameTextBox4.Location = new System.Drawing.Point(133, 137);
            this.FirstNameTextBox4.MaxLength = 32767;
            this.FirstNameTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
            this.FirstNameTextBox4.Modified = false;
            this.FirstNameTextBox4.Multiline = false;
            this.FirstNameTextBox4.Name = "FirstNameTextBox4";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.FirstNameTextBox4.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.FirstNameTextBox4.OnIdleState = stateProperties32;
            this.FirstNameTextBox4.Padding = new System.Windows.Forms.Padding(3);
            this.FirstNameTextBox4.PasswordChar = '\0';
            this.FirstNameTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.FirstNameTextBox4.PlaceholderText = "First Name";
            this.FirstNameTextBox4.ReadOnly = false;
            this.FirstNameTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.FirstNameTextBox4.SelectedText = "";
            this.FirstNameTextBox4.SelectionLength = 0;
            this.FirstNameTextBox4.SelectionStart = 0;
            this.FirstNameTextBox4.ShortcutsEnabled = true;
            this.FirstNameTextBox4.Size = new System.Drawing.Size(260, 39);
            this.FirstNameTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.FirstNameTextBox4.TabIndex = 22;
            this.FirstNameTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.FirstNameTextBox4.TextMarginBottom = 0;
            this.FirstNameTextBox4.TextMarginLeft = 3;
            this.FirstNameTextBox4.TextMarginTop = 1;
            this.FirstNameTextBox4.TextPlaceholder = "First Name";
            this.FirstNameTextBox4.UseSystemPasswordChar = false;
            this.FirstNameTextBox4.WordWrap = true;
            // 
            // Employeeusercontrol
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.Content);
            this.Name = "Employeeusercontrol";
            this.Size = new System.Drawing.Size(1175, 642);
            this.Content.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel Content;
        private Bunifu.UI.WinForms.BunifuTextBox employeeidTextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox salaryTextBox4;
        private Bunifu.UI.WinForms.BunifuTextBox codemelliTextBox3;
        private Bunifu.UI.WinForms.BunifuTextBox ageTextBox2;
        private Bunifu.UI.WinForms.BunifuDropdown employeetypeDropdown1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox lastNameTextBox5;
        private Bunifu.UI.WinForms.BunifuTextBox FirstNameTextBox4;
    }
}
