namespace ParkingProject
{
    partial class ParkingregisterUsereControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ParkingregisterUsereControl));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Content = new System.Windows.Forms.Panel();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.typeofparkingDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.descriptionTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.operatinghoursTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addressTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.capacityTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.numberTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Content.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Content
            // 
            this.Content.Controls.Add(this.bunifuButton2);
            this.Content.Controls.Add(this.bunifuButton1);
            this.Content.Controls.Add(this.typeofparkingDropdown1);
            this.Content.Controls.Add(this.descriptionTextBox6);
            this.Content.Controls.Add(this.operatinghoursTextBox3);
            this.Content.Controls.Add(this.addressTextBox5);
            this.Content.Controls.Add(this.capacityTextBox2);
            this.Content.Controls.Add(this.numberTextBox4);
            this.Content.Controls.Add(this.nameTextBox1);
            this.Content.Controls.Add(this.bunifuPanel1);
            this.Content.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Content.Location = new System.Drawing.Point(0, 0);
            this.Content.Name = "Content";
            this.Content.Size = new System.Drawing.Size(1175, 642);
            this.Content.TabIndex = 0;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Save";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges3;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(410, 565);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton2.TabIndex = 14;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Back";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges4;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(618, 565);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 15;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click_1);
            // 
            // typeofparkingDropdown1
            // 
            this.typeofparkingDropdown1.BackColor = System.Drawing.Color.Transparent;
            this.typeofparkingDropdown1.BackgroundColor = System.Drawing.Color.White;
            this.typeofparkingDropdown1.BorderColor = System.Drawing.Color.Silver;
            this.typeofparkingDropdown1.BorderRadius = 1;
            this.typeofparkingDropdown1.Color = System.Drawing.Color.Silver;
            this.typeofparkingDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.typeofparkingDropdown1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.typeofparkingDropdown1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.typeofparkingDropdown1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.typeofparkingDropdown1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.typeofparkingDropdown1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.typeofparkingDropdown1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.typeofparkingDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.typeofparkingDropdown1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.typeofparkingDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.typeofparkingDropdown1.FillDropDown = true;
            this.typeofparkingDropdown1.FillIndicator = false;
            this.typeofparkingDropdown1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.typeofparkingDropdown1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.typeofparkingDropdown1.ForeColor = System.Drawing.Color.Black;
            this.typeofparkingDropdown1.FormattingEnabled = true;
            this.typeofparkingDropdown1.Icon = null;
            this.typeofparkingDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.typeofparkingDropdown1.IndicatorColor = System.Drawing.Color.DarkGray;
            this.typeofparkingDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.typeofparkingDropdown1.IndicatorThickness = 2;
            this.typeofparkingDropdown1.IsDropdownOpened = false;
            this.typeofparkingDropdown1.ItemBackColor = System.Drawing.Color.White;
            this.typeofparkingDropdown1.ItemBorderColor = System.Drawing.Color.White;
            this.typeofparkingDropdown1.ItemForeColor = System.Drawing.Color.Black;
            this.typeofparkingDropdown1.ItemHeight = 26;
            this.typeofparkingDropdown1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.typeofparkingDropdown1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.typeofparkingDropdown1.Items.AddRange(new object[] {
            "Public",
            "Private",
            "Organizational"});
            this.typeofparkingDropdown1.ItemTopMargin = 3;
            this.typeofparkingDropdown1.Location = new System.Drawing.Point(292, 402);
            this.typeofparkingDropdown1.Name = "typeofparkingDropdown1";
            this.typeofparkingDropdown1.Size = new System.Drawing.Size(260, 32);
            this.typeofparkingDropdown1.TabIndex = 13;
            this.typeofparkingDropdown1.Text = "Type of parking";
            this.typeofparkingDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.typeofparkingDropdown1.TextLeftMargin = 5;
            // 
            // descriptionTextBox6
            // 
            this.descriptionTextBox6.AcceptsReturn = false;
            this.descriptionTextBox6.AcceptsTab = false;
            this.descriptionTextBox6.AnimationSpeed = 200;
            this.descriptionTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.descriptionTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.descriptionTextBox6.AutoSizeHeight = true;
            this.descriptionTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.descriptionTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("descriptionTextBox6.BackgroundImage")));
            this.descriptionTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.descriptionTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.descriptionTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.descriptionTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
            this.descriptionTextBox6.BorderRadius = 1;
            this.descriptionTextBox6.BorderThickness = 1;
            this.descriptionTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.descriptionTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.descriptionTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.descriptionTextBox6.DefaultText = "";
            this.descriptionTextBox6.FillColor = System.Drawing.Color.White;
            this.descriptionTextBox6.HideSelection = true;
            this.descriptionTextBox6.IconLeft = null;
            this.descriptionTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriptionTextBox6.IconPadding = 10;
            this.descriptionTextBox6.IconRight = null;
            this.descriptionTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.descriptionTextBox6.Lines = new string[0];
            this.descriptionTextBox6.Location = new System.Drawing.Point(642, 296);
            this.descriptionTextBox6.MaxLength = 32767;
            this.descriptionTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
            this.descriptionTextBox6.Modified = false;
            this.descriptionTextBox6.Multiline = false;
            this.descriptionTextBox6.Name = "descriptionTextBox6";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriptionTextBox6.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.descriptionTextBox6.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriptionTextBox6.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.descriptionTextBox6.OnIdleState = stateProperties28;
            this.descriptionTextBox6.Padding = new System.Windows.Forms.Padding(3);
            this.descriptionTextBox6.PasswordChar = '\0';
            this.descriptionTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.descriptionTextBox6.PlaceholderText = "Description";
            this.descriptionTextBox6.ReadOnly = false;
            this.descriptionTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.descriptionTextBox6.SelectedText = "";
            this.descriptionTextBox6.SelectionLength = 0;
            this.descriptionTextBox6.SelectionStart = 0;
            this.descriptionTextBox6.ShortcutsEnabled = true;
            this.descriptionTextBox6.Size = new System.Drawing.Size(260, 39);
            this.descriptionTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.descriptionTextBox6.TabIndex = 7;
            this.descriptionTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.descriptionTextBox6.TextMarginBottom = 0;
            this.descriptionTextBox6.TextMarginLeft = 3;
            this.descriptionTextBox6.TextMarginTop = 1;
            this.descriptionTextBox6.TextPlaceholder = "Description";
            this.descriptionTextBox6.UseSystemPasswordChar = false;
            this.descriptionTextBox6.WordWrap = true;
            // 
            // operatinghoursTextBox3
            // 
            this.operatinghoursTextBox3.AcceptsReturn = false;
            this.operatinghoursTextBox3.AcceptsTab = false;
            this.operatinghoursTextBox3.AnimationSpeed = 200;
            this.operatinghoursTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.operatinghoursTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.operatinghoursTextBox3.AutoSizeHeight = true;
            this.operatinghoursTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.operatinghoursTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("operatinghoursTextBox3.BackgroundImage")));
            this.operatinghoursTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.operatinghoursTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.operatinghoursTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.operatinghoursTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.operatinghoursTextBox3.BorderRadius = 1;
            this.operatinghoursTextBox3.BorderThickness = 1;
            this.operatinghoursTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.operatinghoursTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.operatinghoursTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.operatinghoursTextBox3.DefaultText = "";
            this.operatinghoursTextBox3.FillColor = System.Drawing.Color.White;
            this.operatinghoursTextBox3.HideSelection = true;
            this.operatinghoursTextBox3.IconLeft = null;
            this.operatinghoursTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.operatinghoursTextBox3.IconPadding = 10;
            this.operatinghoursTextBox3.IconRight = null;
            this.operatinghoursTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.operatinghoursTextBox3.Lines = new string[0];
            this.operatinghoursTextBox3.Location = new System.Drawing.Point(642, 193);
            this.operatinghoursTextBox3.MaxLength = 32767;
            this.operatinghoursTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.operatinghoursTextBox3.Modified = false;
            this.operatinghoursTextBox3.Multiline = false;
            this.operatinghoursTextBox3.Name = "operatinghoursTextBox3";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.operatinghoursTextBox3.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.operatinghoursTextBox3.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.operatinghoursTextBox3.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.operatinghoursTextBox3.OnIdleState = stateProperties32;
            this.operatinghoursTextBox3.Padding = new System.Windows.Forms.Padding(3);
            this.operatinghoursTextBox3.PasswordChar = '\0';
            this.operatinghoursTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.operatinghoursTextBox3.PlaceholderText = "Operating hours";
            this.operatinghoursTextBox3.ReadOnly = false;
            this.operatinghoursTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.operatinghoursTextBox3.SelectedText = "";
            this.operatinghoursTextBox3.SelectionLength = 0;
            this.operatinghoursTextBox3.SelectionStart = 0;
            this.operatinghoursTextBox3.ShortcutsEnabled = true;
            this.operatinghoursTextBox3.Size = new System.Drawing.Size(260, 39);
            this.operatinghoursTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.operatinghoursTextBox3.TabIndex = 8;
            this.operatinghoursTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.operatinghoursTextBox3.TextMarginBottom = 0;
            this.operatinghoursTextBox3.TextMarginLeft = 3;
            this.operatinghoursTextBox3.TextMarginTop = 1;
            this.operatinghoursTextBox3.TextPlaceholder = "Operating hours";
            this.operatinghoursTextBox3.UseSystemPasswordChar = false;
            this.operatinghoursTextBox3.WordWrap = true;
            // 
            // addressTextBox5
            // 
            this.addressTextBox5.AcceptsReturn = false;
            this.addressTextBox5.AcceptsTab = false;
            this.addressTextBox5.AnimationSpeed = 200;
            this.addressTextBox5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressTextBox5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressTextBox5.AutoSizeHeight = true;
            this.addressTextBox5.BackColor = System.Drawing.Color.Transparent;
            this.addressTextBox5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressTextBox5.BackgroundImage")));
            this.addressTextBox5.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressTextBox5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressTextBox5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressTextBox5.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressTextBox5.BorderRadius = 1;
            this.addressTextBox5.BorderThickness = 1;
            this.addressTextBox5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTextBox5.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressTextBox5.DefaultText = "";
            this.addressTextBox5.FillColor = System.Drawing.Color.White;
            this.addressTextBox5.HideSelection = true;
            this.addressTextBox5.IconLeft = null;
            this.addressTextBox5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTextBox5.IconPadding = 10;
            this.addressTextBox5.IconRight = null;
            this.addressTextBox5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTextBox5.Lines = new string[0];
            this.addressTextBox5.Location = new System.Drawing.Point(642, 101);
            this.addressTextBox5.MaxLength = 32767;
            this.addressTextBox5.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressTextBox5.Modified = false;
            this.addressTextBox5.Multiline = false;
            this.addressTextBox5.Name = "addressTextBox5";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTextBox5.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressTextBox5.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTextBox5.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTextBox5.OnIdleState = stateProperties36;
            this.addressTextBox5.Padding = new System.Windows.Forms.Padding(3);
            this.addressTextBox5.PasswordChar = '\0';
            this.addressTextBox5.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressTextBox5.PlaceholderText = "Address";
            this.addressTextBox5.ReadOnly = false;
            this.addressTextBox5.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressTextBox5.SelectedText = "";
            this.addressTextBox5.SelectionLength = 0;
            this.addressTextBox5.SelectionStart = 0;
            this.addressTextBox5.ShortcutsEnabled = true;
            this.addressTextBox5.Size = new System.Drawing.Size(260, 39);
            this.addressTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressTextBox5.TabIndex = 9;
            this.addressTextBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressTextBox5.TextMarginBottom = 0;
            this.addressTextBox5.TextMarginLeft = 3;
            this.addressTextBox5.TextMarginTop = 1;
            this.addressTextBox5.TextPlaceholder = "Address";
            this.addressTextBox5.UseSystemPasswordChar = false;
            this.addressTextBox5.WordWrap = true;
            // 
            // capacityTextBox2
            // 
            this.capacityTextBox2.AcceptsReturn = false;
            this.capacityTextBox2.AcceptsTab = false;
            this.capacityTextBox2.AnimationSpeed = 200;
            this.capacityTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.capacityTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.capacityTextBox2.AutoSizeHeight = true;
            this.capacityTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.capacityTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("capacityTextBox2.BackgroundImage")));
            this.capacityTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.capacityTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.capacityTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.capacityTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.capacityTextBox2.BorderRadius = 1;
            this.capacityTextBox2.BorderThickness = 1;
            this.capacityTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.capacityTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.capacityTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.capacityTextBox2.DefaultText = "";
            this.capacityTextBox2.FillColor = System.Drawing.Color.White;
            this.capacityTextBox2.HideSelection = true;
            this.capacityTextBox2.IconLeft = null;
            this.capacityTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.capacityTextBox2.IconPadding = 10;
            this.capacityTextBox2.IconRight = null;
            this.capacityTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.capacityTextBox2.Lines = new string[0];
            this.capacityTextBox2.Location = new System.Drawing.Point(292, 296);
            this.capacityTextBox2.MaxLength = 32767;
            this.capacityTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.capacityTextBox2.Modified = false;
            this.capacityTextBox2.Multiline = false;
            this.capacityTextBox2.Name = "capacityTextBox2";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.capacityTextBox2.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.capacityTextBox2.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.capacityTextBox2.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.capacityTextBox2.OnIdleState = stateProperties40;
            this.capacityTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.capacityTextBox2.PasswordChar = '\0';
            this.capacityTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.capacityTextBox2.PlaceholderText = "Capacity";
            this.capacityTextBox2.ReadOnly = false;
            this.capacityTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.capacityTextBox2.SelectedText = "";
            this.capacityTextBox2.SelectionLength = 0;
            this.capacityTextBox2.SelectionStart = 0;
            this.capacityTextBox2.ShortcutsEnabled = true;
            this.capacityTextBox2.Size = new System.Drawing.Size(260, 39);
            this.capacityTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.capacityTextBox2.TabIndex = 10;
            this.capacityTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.capacityTextBox2.TextMarginBottom = 0;
            this.capacityTextBox2.TextMarginLeft = 3;
            this.capacityTextBox2.TextMarginTop = 1;
            this.capacityTextBox2.TextPlaceholder = "Capacity";
            this.capacityTextBox2.UseSystemPasswordChar = false;
            this.capacityTextBox2.WordWrap = true;
            // 
            // numberTextBox4
            // 
            this.numberTextBox4.AcceptsReturn = false;
            this.numberTextBox4.AcceptsTab = false;
            this.numberTextBox4.AnimationSpeed = 200;
            this.numberTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numberTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numberTextBox4.AutoSizeHeight = true;
            this.numberTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.numberTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numberTextBox4.BackgroundImage")));
            this.numberTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.numberTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numberTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numberTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.numberTextBox4.BorderRadius = 1;
            this.numberTextBox4.BorderThickness = 1;
            this.numberTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numberTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.numberTextBox4.DefaultText = "";
            this.numberTextBox4.FillColor = System.Drawing.Color.White;
            this.numberTextBox4.HideSelection = true;
            this.numberTextBox4.IconLeft = null;
            this.numberTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextBox4.IconPadding = 10;
            this.numberTextBox4.IconRight = null;
            this.numberTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numberTextBox4.Lines = new string[0];
            this.numberTextBox4.Location = new System.Drawing.Point(292, 193);
            this.numberTextBox4.MaxLength = 32767;
            this.numberTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
            this.numberTextBox4.Modified = false;
            this.numberTextBox4.Multiline = false;
            this.numberTextBox4.Name = "numberTextBox4";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextBox4.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numberTextBox4.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextBox4.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numberTextBox4.OnIdleState = stateProperties44;
            this.numberTextBox4.Padding = new System.Windows.Forms.Padding(3);
            this.numberTextBox4.PasswordChar = '\0';
            this.numberTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numberTextBox4.PlaceholderText = "Number";
            this.numberTextBox4.ReadOnly = false;
            this.numberTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numberTextBox4.SelectedText = "";
            this.numberTextBox4.SelectionLength = 0;
            this.numberTextBox4.SelectionStart = 0;
            this.numberTextBox4.ShortcutsEnabled = true;
            this.numberTextBox4.Size = new System.Drawing.Size(260, 39);
            this.numberTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numberTextBox4.TabIndex = 11;
            this.numberTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numberTextBox4.TextMarginBottom = 0;
            this.numberTextBox4.TextMarginLeft = 3;
            this.numberTextBox4.TextMarginTop = 1;
            this.numberTextBox4.TextPlaceholder = "Number";
            this.numberTextBox4.UseSystemPasswordChar = false;
            this.numberTextBox4.WordWrap = true;
            // 
            // nameTextBox1
            // 
            this.nameTextBox1.AcceptsReturn = false;
            this.nameTextBox1.AcceptsTab = false;
            this.nameTextBox1.AnimationSpeed = 200;
            this.nameTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameTextBox1.AutoSizeHeight = true;
            this.nameTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.nameTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameTextBox1.BackgroundImage")));
            this.nameTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameTextBox1.BorderRadius = 1;
            this.nameTextBox1.BorderThickness = 1;
            this.nameTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameTextBox1.DefaultText = "";
            this.nameTextBox1.FillColor = System.Drawing.Color.White;
            this.nameTextBox1.HideSelection = true;
            this.nameTextBox1.IconLeft = null;
            this.nameTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox1.IconPadding = 10;
            this.nameTextBox1.IconRight = null;
            this.nameTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTextBox1.Lines = new string[0];
            this.nameTextBox1.Location = new System.Drawing.Point(292, 101);
            this.nameTextBox1.MaxLength = 32767;
            this.nameTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameTextBox1.Modified = false;
            this.nameTextBox1.Multiline = false;
            this.nameTextBox1.Name = "nameTextBox1";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox1.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameTextBox1.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox1.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTextBox1.OnIdleState = stateProperties48;
            this.nameTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.nameTextBox1.PasswordChar = '\0';
            this.nameTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameTextBox1.PlaceholderText = "Name";
            this.nameTextBox1.ReadOnly = false;
            this.nameTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameTextBox1.SelectedText = "";
            this.nameTextBox1.SelectionLength = 0;
            this.nameTextBox1.SelectionStart = 0;
            this.nameTextBox1.ShortcutsEnabled = true;
            this.nameTextBox1.Size = new System.Drawing.Size(260, 39);
            this.nameTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameTextBox1.TabIndex = 12;
            this.nameTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameTextBox1.TextMarginBottom = 0;
            this.nameTextBox1.TextMarginLeft = 3;
            this.nameTextBox1.TextMarginTop = 1;
            this.nameTextBox1.TextPlaceholder = "Name";
            this.nameTextBox1.UseSystemPasswordChar = false;
            this.nameTextBox1.WordWrap = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1175, 43);
            this.bunifuPanel1.TabIndex = 6;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(89, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(108, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Parking register";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ParkingregisterUsereControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.Content);
            this.Name = "ParkingregisterUsereControl";
            this.Size = new System.Drawing.Size(1175, 642);
            this.Content.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel Content;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuDropdown typeofparkingDropdown1;
        private Bunifu.UI.WinForms.BunifuTextBox descriptionTextBox6;
        private Bunifu.UI.WinForms.BunifuTextBox operatinghoursTextBox3;
        private Bunifu.UI.WinForms.BunifuTextBox addressTextBox5;
        private Bunifu.UI.WinForms.BunifuTextBox capacityTextBox2;
        private Bunifu.UI.WinForms.BunifuTextBox numberTextBox4;
        private Bunifu.UI.WinForms.BunifuTextBox nameTextBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}
