namespace ParkingProject
{
    partial class UserRegister
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserRegister));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.guna2CircleButton1 = new Guna.UI2.WinForms.Guna2CircleButton();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ProductKeyTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SystemIDTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TypeuserDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.usernameTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RepeatpasswordTextBox7 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.passwordTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.fullnameTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.guna2CircleButton1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(725, 43);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(24, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(40, 37);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(89, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(208, 19);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Activation & Registration Form";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // guna2CircleButton1
            // 
            this.guna2CircleButton1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.guna2CircleButton1.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2CircleButton1.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2CircleButton1.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2CircleButton1.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2CircleButton1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(58)))), ((int)(((byte)(70)))));
            this.guna2CircleButton1.Font = new System.Drawing.Font("Segoe UI", 20F, System.Drawing.FontStyle.Bold);
            this.guna2CircleButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(122)))), ((int)(((byte)(148)))));
            this.guna2CircleButton1.Location = new System.Drawing.Point(681, 1);
            this.guna2CircleButton1.Name = "guna2CircleButton1";
            this.guna2CircleButton1.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.guna2CircleButton1.Size = new System.Drawing.Size(40, 37);
            this.guna2CircleButton1.TabIndex = 2;
            this.guna2CircleButton1.Text = "X";
            this.guna2CircleButton1.Click += new System.EventHandler(this.guna2CircleButton1_Click);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuButton1);
            this.bunifuGroupBox1.Controls.Add(this.ProductKeyTextBox3);
            this.bunifuGroupBox1.Controls.Add(this.SystemIDTextBox1);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(12, 60);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(697, 240);
            this.bunifuGroupBox1.TabIndex = 1;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Activation";
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Activate";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(278, 164);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 1;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // ProductKeyTextBox3
            // 
            this.ProductKeyTextBox3.AcceptsReturn = false;
            this.ProductKeyTextBox3.AcceptsTab = false;
            this.ProductKeyTextBox3.AnimationSpeed = 200;
            this.ProductKeyTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ProductKeyTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ProductKeyTextBox3.AutoSizeHeight = true;
            this.ProductKeyTextBox3.BackColor = System.Drawing.Color.Transparent;
            this.ProductKeyTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ProductKeyTextBox3.BackgroundImage")));
            this.ProductKeyTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ProductKeyTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ProductKeyTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ProductKeyTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
            this.ProductKeyTextBox3.BorderRadius = 1;
            this.ProductKeyTextBox3.BorderThickness = 1;
            this.ProductKeyTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ProductKeyTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductKeyTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.ProductKeyTextBox3.DefaultText = "";
            this.ProductKeyTextBox3.FillColor = System.Drawing.Color.White;
            this.ProductKeyTextBox3.HideSelection = true;
            this.ProductKeyTextBox3.IconLeft = null;
            this.ProductKeyTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductKeyTextBox3.IconPadding = 10;
            this.ProductKeyTextBox3.IconRight = null;
            this.ProductKeyTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ProductKeyTextBox3.Lines = new string[0];
            this.ProductKeyTextBox3.Location = new System.Drawing.Point(164, 99);
            this.ProductKeyTextBox3.MaxLength = 32767;
            this.ProductKeyTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
            this.ProductKeyTextBox3.Modified = false;
            this.ProductKeyTextBox3.Multiline = false;
            this.ProductKeyTextBox3.Name = "ProductKeyTextBox3";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductKeyTextBox3.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ProductKeyTextBox3.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductKeyTextBox3.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ProductKeyTextBox3.OnIdleState = stateProperties4;
            this.ProductKeyTextBox3.Padding = new System.Windows.Forms.Padding(3);
            this.ProductKeyTextBox3.PasswordChar = '\0';
            this.ProductKeyTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ProductKeyTextBox3.PlaceholderText = "Product Key";
            this.ProductKeyTextBox3.ReadOnly = false;
            this.ProductKeyTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ProductKeyTextBox3.SelectedText = "";
            this.ProductKeyTextBox3.SelectionLength = 0;
            this.ProductKeyTextBox3.SelectionStart = 0;
            this.ProductKeyTextBox3.ShortcutsEnabled = true;
            this.ProductKeyTextBox3.Size = new System.Drawing.Size(397, 41);
            this.ProductKeyTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ProductKeyTextBox3.TabIndex = 0;
            this.ProductKeyTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ProductKeyTextBox3.TextMarginBottom = 0;
            this.ProductKeyTextBox3.TextMarginLeft = 3;
            this.ProductKeyTextBox3.TextMarginTop = 1;
            this.ProductKeyTextBox3.TextPlaceholder = "Product Key";
            this.ProductKeyTextBox3.UseSystemPasswordChar = false;
            this.ProductKeyTextBox3.WordWrap = true;
            this.ProductKeyTextBox3.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // SystemIDTextBox1
            // 
            this.SystemIDTextBox1.AcceptsReturn = false;
            this.SystemIDTextBox1.AcceptsTab = false;
            this.SystemIDTextBox1.AnimationSpeed = 200;
            this.SystemIDTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.SystemIDTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.SystemIDTextBox1.AutoSizeHeight = true;
            this.SystemIDTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.SystemIDTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SystemIDTextBox1.BackgroundImage")));
            this.SystemIDTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.SystemIDTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SystemIDTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SystemIDTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.SystemIDTextBox1.BorderRadius = 1;
            this.SystemIDTextBox1.BorderThickness = 1;
            this.SystemIDTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.SystemIDTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.SystemIDTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.SystemIDTextBox1.DefaultText = "";
            this.SystemIDTextBox1.FillColor = System.Drawing.Color.White;
            this.SystemIDTextBox1.HideSelection = true;
            this.SystemIDTextBox1.IconLeft = null;
            this.SystemIDTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.SystemIDTextBox1.IconPadding = 10;
            this.SystemIDTextBox1.IconRight = null;
            this.SystemIDTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.SystemIDTextBox1.Lines = new string[0];
            this.SystemIDTextBox1.Location = new System.Drawing.Point(164, 40);
            this.SystemIDTextBox1.MaxLength = 32767;
            this.SystemIDTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.SystemIDTextBox1.Modified = false;
            this.SystemIDTextBox1.Multiline = false;
            this.SystemIDTextBox1.Name = "SystemIDTextBox1";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SystemIDTextBox1.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.SystemIDTextBox1.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SystemIDTextBox1.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.SystemIDTextBox1.OnIdleState = stateProperties8;
            this.SystemIDTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.SystemIDTextBox1.PasswordChar = '\0';
            this.SystemIDTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.SystemIDTextBox1.PlaceholderText = "System ID";
            this.SystemIDTextBox1.ReadOnly = true;
            this.SystemIDTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.SystemIDTextBox1.SelectedText = "";
            this.SystemIDTextBox1.SelectionLength = 0;
            this.SystemIDTextBox1.SelectionStart = 0;
            this.SystemIDTextBox1.ShortcutsEnabled = true;
            this.SystemIDTextBox1.Size = new System.Drawing.Size(397, 41);
            this.SystemIDTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.SystemIDTextBox1.TabIndex = 0;
            this.SystemIDTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.SystemIDTextBox1.TextMarginBottom = 0;
            this.SystemIDTextBox1.TextMarginLeft = 3;
            this.SystemIDTextBox1.TextMarginTop = 1;
            this.SystemIDTextBox1.TextPlaceholder = "System ID";
            this.SystemIDTextBox1.UseSystemPasswordChar = false;
            this.SystemIDTextBox1.WordWrap = true;
            this.SystemIDTextBox1.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.bunifuButton2);
            this.bunifuGroupBox2.Controls.Add(this.TypeuserDropdown1);
            this.bunifuGroupBox2.Controls.Add(this.usernameTextBox4);
            this.bunifuGroupBox2.Controls.Add(this.RepeatpasswordTextBox7);
            this.bunifuGroupBox2.Controls.Add(this.passwordTextBox6);
            this.bunifuGroupBox2.Controls.Add(this.fullnameTextBox2);
            this.bunifuGroupBox2.Enabled = false;
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(12, 311);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(697, 270);
            this.bunifuGroupBox2.TabIndex = 1;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Registration";
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Register";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges2;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = null;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(271, 217);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(124)))), ((int)(((byte)(245)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton2.TabIndex = 1;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // TypeuserDropdown1
            // 
            this.TypeuserDropdown1.BackColor = System.Drawing.Color.Transparent;
            this.TypeuserDropdown1.BackgroundColor = System.Drawing.Color.White;
            this.TypeuserDropdown1.BorderColor = System.Drawing.Color.Silver;
            this.TypeuserDropdown1.BorderRadius = 1;
            this.TypeuserDropdown1.Color = System.Drawing.Color.Silver;
            this.TypeuserDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.TypeuserDropdown1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.TypeuserDropdown1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TypeuserDropdown1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.TypeuserDropdown1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.TypeuserDropdown1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.TypeuserDropdown1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.TypeuserDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.TypeuserDropdown1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.TypeuserDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.TypeuserDropdown1.FillDropDown = true;
            this.TypeuserDropdown1.FillIndicator = false;
            this.TypeuserDropdown1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.TypeuserDropdown1.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            this.TypeuserDropdown1.ForeColor = System.Drawing.Color.Black;
            this.TypeuserDropdown1.FormattingEnabled = true;
            this.TypeuserDropdown1.Icon = null;
            this.TypeuserDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.TypeuserDropdown1.IndicatorColor = System.Drawing.Color.DarkGray;
            this.TypeuserDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.TypeuserDropdown1.IndicatorThickness = 2;
            this.TypeuserDropdown1.IsDropdownOpened = false;
            this.TypeuserDropdown1.ItemBackColor = System.Drawing.Color.White;
            this.TypeuserDropdown1.ItemBorderColor = System.Drawing.Color.White;
            this.TypeuserDropdown1.ItemForeColor = System.Drawing.Color.Black;
            this.TypeuserDropdown1.ItemHeight = 26;
            this.TypeuserDropdown1.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.TypeuserDropdown1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.TypeuserDropdown1.Items.AddRange(new object[] {
            "Regular User",
            "Admin User"});
            this.TypeuserDropdown1.ItemTopMargin = 3;
            this.TypeuserDropdown1.Location = new System.Drawing.Point(25, 96);
            this.TypeuserDropdown1.Name = "TypeuserDropdown1";
            this.TypeuserDropdown1.Size = new System.Drawing.Size(275, 32);
            this.TypeuserDropdown1.TabIndex = 1;
            this.TypeuserDropdown1.Text = "Type of User";
            this.TypeuserDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.TypeuserDropdown1.TextLeftMargin = 5;
            // 
            // usernameTextBox4
            // 
            this.usernameTextBox4.AcceptsReturn = false;
            this.usernameTextBox4.AcceptsTab = false;
            this.usernameTextBox4.AnimationSpeed = 200;
            this.usernameTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.usernameTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.usernameTextBox4.AutoSizeHeight = true;
            this.usernameTextBox4.BackColor = System.Drawing.Color.Transparent;
            this.usernameTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usernameTextBox4.BackgroundImage")));
            this.usernameTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.usernameTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.usernameTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.usernameTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
            this.usernameTextBox4.BorderRadius = 1;
            this.usernameTextBox4.BorderThickness = 1;
            this.usernameTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.usernameTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.usernameTextBox4.DefaultText = "";
            this.usernameTextBox4.FillColor = System.Drawing.Color.White;
            this.usernameTextBox4.HideSelection = true;
            this.usernameTextBox4.IconLeft = null;
            this.usernameTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox4.IconPadding = 10;
            this.usernameTextBox4.IconRight = null;
            this.usernameTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox4.Lines = new string[0];
            this.usernameTextBox4.Location = new System.Drawing.Point(395, 31);
            this.usernameTextBox4.MaxLength = 32767;
            this.usernameTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
            this.usernameTextBox4.Modified = false;
            this.usernameTextBox4.Multiline = false;
            this.usernameTextBox4.Name = "usernameTextBox4";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox4.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.usernameTextBox4.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox4.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox4.OnIdleState = stateProperties12;
            this.usernameTextBox4.Padding = new System.Windows.Forms.Padding(3);
            this.usernameTextBox4.PasswordChar = '\0';
            this.usernameTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.usernameTextBox4.PlaceholderText = "Username";
            this.usernameTextBox4.ReadOnly = false;
            this.usernameTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.usernameTextBox4.SelectedText = "";
            this.usernameTextBox4.SelectionLength = 0;
            this.usernameTextBox4.SelectionStart = 0;
            this.usernameTextBox4.ShortcutsEnabled = true;
            this.usernameTextBox4.Size = new System.Drawing.Size(275, 41);
            this.usernameTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.usernameTextBox4.TabIndex = 0;
            this.usernameTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.usernameTextBox4.TextMarginBottom = 0;
            this.usernameTextBox4.TextMarginLeft = 3;
            this.usernameTextBox4.TextMarginTop = 1;
            this.usernameTextBox4.TextPlaceholder = "Username";
            this.usernameTextBox4.UseSystemPasswordChar = false;
            this.usernameTextBox4.WordWrap = true;
            // 
            // RepeatpasswordTextBox7
            // 
            this.RepeatpasswordTextBox7.AcceptsReturn = false;
            this.RepeatpasswordTextBox7.AcceptsTab = false;
            this.RepeatpasswordTextBox7.AnimationSpeed = 200;
            this.RepeatpasswordTextBox7.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.RepeatpasswordTextBox7.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.RepeatpasswordTextBox7.AutoSizeHeight = true;
            this.RepeatpasswordTextBox7.BackColor = System.Drawing.Color.Transparent;
            this.RepeatpasswordTextBox7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RepeatpasswordTextBox7.BackgroundImage")));
            this.RepeatpasswordTextBox7.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.RepeatpasswordTextBox7.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RepeatpasswordTextBox7.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.RepeatpasswordTextBox7.BorderColorIdle = System.Drawing.Color.Silver;
            this.RepeatpasswordTextBox7.BorderRadius = 1;
            this.RepeatpasswordTextBox7.BorderThickness = 1;
            this.RepeatpasswordTextBox7.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.RepeatpasswordTextBox7.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.RepeatpasswordTextBox7.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.RepeatpasswordTextBox7.DefaultText = "";
            this.RepeatpasswordTextBox7.FillColor = System.Drawing.Color.White;
            this.RepeatpasswordTextBox7.HideSelection = true;
            this.RepeatpasswordTextBox7.IconLeft = null;
            this.RepeatpasswordTextBox7.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.RepeatpasswordTextBox7.IconPadding = 10;
            this.RepeatpasswordTextBox7.IconRight = null;
            this.RepeatpasswordTextBox7.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.RepeatpasswordTextBox7.Lines = new string[0];
            this.RepeatpasswordTextBox7.Location = new System.Drawing.Point(395, 143);
            this.RepeatpasswordTextBox7.MaxLength = 32767;
            this.RepeatpasswordTextBox7.MinimumSize = new System.Drawing.Size(1, 1);
            this.RepeatpasswordTextBox7.Modified = false;
            this.RepeatpasswordTextBox7.Multiline = false;
            this.RepeatpasswordTextBox7.Name = "RepeatpasswordTextBox7";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RepeatpasswordTextBox7.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.RepeatpasswordTextBox7.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RepeatpasswordTextBox7.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.RepeatpasswordTextBox7.OnIdleState = stateProperties16;
            this.RepeatpasswordTextBox7.Padding = new System.Windows.Forms.Padding(3);
            this.RepeatpasswordTextBox7.PasswordChar = '\0';
            this.RepeatpasswordTextBox7.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.RepeatpasswordTextBox7.PlaceholderText = "Repeat Password";
            this.RepeatpasswordTextBox7.ReadOnly = false;
            this.RepeatpasswordTextBox7.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.RepeatpasswordTextBox7.SelectedText = "";
            this.RepeatpasswordTextBox7.SelectionLength = 0;
            this.RepeatpasswordTextBox7.SelectionStart = 0;
            this.RepeatpasswordTextBox7.ShortcutsEnabled = true;
            this.RepeatpasswordTextBox7.Size = new System.Drawing.Size(275, 41);
            this.RepeatpasswordTextBox7.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.RepeatpasswordTextBox7.TabIndex = 0;
            this.RepeatpasswordTextBox7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.RepeatpasswordTextBox7.TextMarginBottom = 0;
            this.RepeatpasswordTextBox7.TextMarginLeft = 3;
            this.RepeatpasswordTextBox7.TextMarginTop = 1;
            this.RepeatpasswordTextBox7.TextPlaceholder = "Repeat Password";
            this.RepeatpasswordTextBox7.UseSystemPasswordChar = false;
            this.RepeatpasswordTextBox7.WordWrap = true;
            // 
            // passwordTextBox6
            // 
            this.passwordTextBox6.AcceptsReturn = false;
            this.passwordTextBox6.AcceptsTab = false;
            this.passwordTextBox6.AnimationSpeed = 200;
            this.passwordTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordTextBox6.AutoSizeHeight = true;
            this.passwordTextBox6.BackColor = System.Drawing.Color.Transparent;
            this.passwordTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordTextBox6.BackgroundImage")));
            this.passwordTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.passwordTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.passwordTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.passwordTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
            this.passwordTextBox6.BorderRadius = 1;
            this.passwordTextBox6.BorderThickness = 1;
            this.passwordTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.passwordTextBox6.DefaultText = "";
            this.passwordTextBox6.FillColor = System.Drawing.Color.White;
            this.passwordTextBox6.HideSelection = true;
            this.passwordTextBox6.IconLeft = null;
            this.passwordTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTextBox6.IconPadding = 10;
            this.passwordTextBox6.IconRight = null;
            this.passwordTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTextBox6.Lines = new string[0];
            this.passwordTextBox6.Location = new System.Drawing.Point(395, 87);
            this.passwordTextBox6.MaxLength = 32767;
            this.passwordTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordTextBox6.Modified = false;
            this.passwordTextBox6.Multiline = false;
            this.passwordTextBox6.Name = "passwordTextBox6";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTextBox6.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.passwordTextBox6.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTextBox6.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTextBox6.OnIdleState = stateProperties20;
            this.passwordTextBox6.Padding = new System.Windows.Forms.Padding(3);
            this.passwordTextBox6.PasswordChar = '\0';
            this.passwordTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordTextBox6.PlaceholderText = "Password";
            this.passwordTextBox6.ReadOnly = false;
            this.passwordTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordTextBox6.SelectedText = "";
            this.passwordTextBox6.SelectionLength = 0;
            this.passwordTextBox6.SelectionStart = 0;
            this.passwordTextBox6.ShortcutsEnabled = true;
            this.passwordTextBox6.Size = new System.Drawing.Size(275, 41);
            this.passwordTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.passwordTextBox6.TabIndex = 0;
            this.passwordTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordTextBox6.TextMarginBottom = 0;
            this.passwordTextBox6.TextMarginLeft = 3;
            this.passwordTextBox6.TextMarginTop = 1;
            this.passwordTextBox6.TextPlaceholder = "Password";
            this.passwordTextBox6.UseSystemPasswordChar = false;
            this.passwordTextBox6.WordWrap = true;
            // 
            // fullnameTextBox2
            // 
            this.fullnameTextBox2.AcceptsReturn = false;
            this.fullnameTextBox2.AcceptsTab = false;
            this.fullnameTextBox2.AnimationSpeed = 200;
            this.fullnameTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.fullnameTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.fullnameTextBox2.AutoSizeHeight = true;
            this.fullnameTextBox2.BackColor = System.Drawing.Color.Transparent;
            this.fullnameTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fullnameTextBox2.BackgroundImage")));
            this.fullnameTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.fullnameTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.fullnameTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.fullnameTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
            this.fullnameTextBox2.BorderRadius = 1;
            this.fullnameTextBox2.BorderThickness = 1;
            this.fullnameTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.fullnameTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fullnameTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 10.5F);
            this.fullnameTextBox2.DefaultText = "";
            this.fullnameTextBox2.FillColor = System.Drawing.Color.White;
            this.fullnameTextBox2.HideSelection = true;
            this.fullnameTextBox2.IconLeft = null;
            this.fullnameTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.fullnameTextBox2.IconPadding = 10;
            this.fullnameTextBox2.IconRight = null;
            this.fullnameTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.fullnameTextBox2.Lines = new string[0];
            this.fullnameTextBox2.Location = new System.Drawing.Point(25, 31);
            this.fullnameTextBox2.MaxLength = 32767;
            this.fullnameTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
            this.fullnameTextBox2.Modified = false;
            this.fullnameTextBox2.Multiline = false;
            this.fullnameTextBox2.Name = "fullnameTextBox2";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fullnameTextBox2.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.fullnameTextBox2.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fullnameTextBox2.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fullnameTextBox2.OnIdleState = stateProperties24;
            this.fullnameTextBox2.Padding = new System.Windows.Forms.Padding(3);
            this.fullnameTextBox2.PasswordChar = '\0';
            this.fullnameTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fullnameTextBox2.PlaceholderText = "Full name";
            this.fullnameTextBox2.ReadOnly = false;
            this.fullnameTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.fullnameTextBox2.SelectedText = "";
            this.fullnameTextBox2.SelectionLength = 0;
            this.fullnameTextBox2.SelectionStart = 0;
            this.fullnameTextBox2.ShortcutsEnabled = true;
            this.fullnameTextBox2.Size = new System.Drawing.Size(275, 41);
            this.fullnameTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.fullnameTextBox2.TabIndex = 0;
            this.fullnameTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.fullnameTextBox2.TextMarginBottom = 0;
            this.fullnameTextBox2.TextMarginLeft = 3;
            this.fullnameTextBox2.TextMarginTop = 1;
            this.fullnameTextBox2.TextPlaceholder = "Full name";
            this.fullnameTextBox2.UseSystemPasswordChar = false;
            this.fullnameTextBox2.WordWrap = true;
            // 
            // UserRegister
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(249)))), ((int)(((byte)(253)))));
            this.ClientSize = new System.Drawing.Size(725, 609);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "UserRegister";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "UserRegister";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Guna.UI2.WinForms.Guna2CircleButton guna2CircleButton1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuTextBox SystemIDTextBox1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuTextBox fullnameTextBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuTextBox ProductKeyTextBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuDropdown TypeuserDropdown1;
        private Bunifu.UI.WinForms.BunifuTextBox usernameTextBox4;
        private Bunifu.UI.WinForms.BunifuTextBox RepeatpasswordTextBox7;
        private Bunifu.UI.WinForms.BunifuTextBox passwordTextBox6;
    }
}